services:
  load_blancer1:
    image: nginx:latest
    networks:
      - lbalancer-network
    ports:
      - "8081:80"
  
  load_blancer2:
    image: nginx:latest
    networks:
      - lbalancer-network
    ports:
      - "8082:80"
  
  load_blancer3:
    image: nginx:latest
    networks:
      - lbalancer-network
    ports:
      - "8083:80"

  redis:
    image: redis:latest
    networks:
      - cache-network

networks:
  lbalancer-network:
  cache-network:
